### ISSUE TITLE
[Suggestion]: Block animations

### ISSUE THREAD

**Issue by slava110** [Fuzss/betteranimationscollection#15]
### Suggestion (Required)

Hi. In Minecraft doors and trapdoors are too boring IMO. Instantly opening, closing, meh. I think it would be cool to have block animations in the mod too. Animations for doors, trapdoors, levers, buttons, etc.
Like in this mod (1.7.10):
https://www.curseforge.com/minecraft/mc-mods/gobbobs-animated-blocks/screenshots

**Comment by Fuzss** [comment]
Thanks for the suggestion!

I know of this mod and I looked into adding such capabilities to BAC in the past. Unfortunately due to the changes in Minecraft 1.8 (the introduction of the baked models system) something like this is only possible by making changes deep down in Minecraft's rendering engine. The effort and research this would take is not worth it for me, especially just for a handful of blocks.
